CREATE DATABASE QuanLyVatLieu;
GO
USE QuanLyVatLieu;
GO

CREATE TABLE KhachHang (
    MaKH VARCHAR(10) PRIMARY KEY,
    TenKH NVARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(15),
    DiaChi NVARCHAR(255)
);

CREATE TABLE NhaCungCap (
    MaNCC VARCHAR(10) PRIMARY KEY,
    TenNCC NVARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(15),
    DiaChi NVARCHAR(255)
);

CREATE TABLE VatLieu (
    MaVL VARCHAR(10) PRIMARY KEY,
    TenVL NVARCHAR(100) NOT NULL,
    DonViTinh NVARCHAR(20),
    SoLuongTon INT DEFAULT 0,
    GiaBan DECIMAL(18, 2)
);

CREATE TABLE DonHang (
    MaDH VARCHAR(10) PRIMARY KEY,
    MaKH VARCHAR(10),
    NgayLap DATETIME DEFAULT GETDATE(),
    TongTien DECIMAL(18, 2) DEFAULT 0,
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);

CREATE TABLE ChiTietDonHang (
    MaDH VARCHAR(10),
    MaVL VARCHAR(10),
    SoLuong INT NOT NULL,
    DonGia DECIMAL(18, 2) NOT NULL,
    PRIMARY KEY (MaDH, MaVL),
    FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH),
    FOREIGN KEY (MaVL) REFERENCES VatLieu(MaVL)
);

CREATE TABLE ChiTietNhaCungCap (
    MaNCC VARCHAR(10),
    MaVL VARCHAR(10),
    SoLuong INT NOT NULL DEFAULT 0,
    GiaNhap DECIMAL(18, 2) NOT NULL,
    PRIMARY KEY (MaNCC, MaVL),
    FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC),
    FOREIGN KEY (MaVL) REFERENCES VatLieu(MaVL)
);
GO